// Errors
export {
  ApplicationError,
  type ApplicationErrorCode,
  ConflictError,
  OperationTimeoutError,
} from "./errors/index.js";

// Events
export {
  EventDispatcher,
  createAgentTextDeltaEvent,
  createAgentReasoningDeltaEvent,
  createAgentToolCallStartEvent,
  createAgentToolCallEndEvent,
  createAgentContextUpdateEvent,
  createAgentTurnStartedEvent,
  createAgentTurnEndEvent,
  createAgentTurnSupersededEvent,
  createAgentCancelRequestedEvent,
  createAgentAskRequestEvent,
  createAgentTodoUpdatedEvent,
  createAgentToolJobStartedEvent,
  createAgentToolJobUpdateEvent,
  createAgentToolJobEndedEvent,
  createLearningUpdatedEvent,
  createJobCompletedEvent,
  createJobFailedEvent,
  createJobStartedEvent,
  createJobCancelledEvent,
  createPipelineStartedEvent,
  createPipelineCompletedEvent,
  createPipelineFailedEvent,
  createPipelineCancelledEvent,
  createPipelineStepUpdatedEvent,
  createAutomationEvent,
  createAcpTextDeltaEvent,
  createAcpThoughtDeltaEvent,
  createAcpToolCallEvent,
  createAcpToolCallUpdateEvent,
  createAcpPlanEvent,
  createAcpPermissionRequestEvent,
  createAcpAskRequestEvent,
  createAcpTurnEndEvent,
  createAcpSessionStateEvent,
  type ApplicationEvent,
  type AgentTextDeltaEvent,
  type AgentReasoningDeltaEvent,
  type AgentToolCallStartEvent,
  type AgentToolCallEndEvent,
  type AgentAskRequestEvent,
  type AgentTodoUpdatedEvent,
  type AgentToolJobStartedEvent,
  type AgentToolJobUpdateEvent,
  type AgentToolJobEndedEvent,
  type AgentContextUpdateEvent,
  type AgentTurnStartedEvent,
  type AgentTurnEndEvent,
  type AgentTurnEndReason,
  type AgentTurnSupersededEvent,
  type AgentCancelRequestedEvent,
  type AgentLearningUpdatedEvent,
  type JobCompletedEvent,
  type JobFailedEvent,
  type JobStartedEvent,
  type JobCancelledEvent,
  type PipelineStartedEvent,
  type PipelineCompletedEvent,
  type PipelineFailedEvent,
  type PipelineCancelledEvent,
  type PipelineStepUpdatedEvent,
  type AutomationEvent,
  type AcpTextDeltaEvent,
  type AcpThoughtDeltaEvent,
  type AcpToolCallEvent,
  type AcpToolCallUpdateEvent,
  type AcpPlanEvent,
  type AcpPermissionRequestEvent,
  type AcpAskRequestEvent,
  type AcpTurnEndEvent,
  type AcpSessionStateEvent,
  type EventHandler,
  type EventHandlerFn,
} from "./events/index.js";

// Messaging
export {
  CommandBus,
  QueryBus,
  type Command,
  type CommandResult,
  type CommandHandler,
  type Query,
  type QueryResult,
  type QueryHandler,
} from "./messaging/index.js";

// Plugin use cases + ports + services
export type {
  PluginRepositoryPort,
  PluginInstallerPort,
  PluginProcessPort,
  ProcessHandle,
  McpClientPort,
  McpClientFactoryPort,
  ToolDescriptor,
  PromptArgumentDescriptor,
  PromptDescriptor,
  PromptResult,
  ResourceDescriptor,
  ResourceReadResult,
  ResourceTemplateDescriptor,
  CompletionReference,
  CompletionResult,
  RootDescriptor,
  ClockPort,
  LoggerPort,
  AutomationClientDeps,
  AutomationRateLimiterPort,
} from "./plugin/index.js";
export {
  PluginOperationQueue,
  PluginRuntimeManager,
  type PluginRuntimeManagerDeps,
  type PluginView,
  type StartPluginOptions,
  type CallToolOptions,
  type WorkspaceSyncResult,
  type PluginLaunchSpec,
  resolveIcon,
  hasPluginUi,
  AutomationEmitRegistry,
  StartPluginHandler,
  StopPluginHandler,
  RestartPluginHandler,
  InstallPluginHandler,
  UninstallPluginHandler,
  SetPluginAutostartHandler,
  ListPluginsHandler,
  GetPluginHandler,
  GetPluginStateHandler,
  type StartPluginCommand,
  type StartPluginResult,
  type StopPluginCommand,
  type StopPluginResult,
  type RestartPluginCommand,
  type RestartPluginResult,
  type InstallPluginCommand,
  type InstallPluginResult,
  type UninstallPluginCommand,
  type UninstallPluginResult,
  type SetPluginAutostartCommand,
  type ListPluginsQuery,
  type ListPluginsResult,
  type PluginListItem,
  type GetPluginQuery,
  type GetPluginResult,
  type GetPluginStateQuery,
  type GetPluginStateResult,
} from "./plugin/index.js";

// Tool use cases
export type { CallToolCommand, CallToolResult, CancelToolCallCommand, CancelToolCallResult, ListToolsQuery, ListToolsResult, ToolItem } from "./tool/index.js";
export { CallToolHandler, CancelToolCallHandler, ListToolsHandler } from "./tool/index.js";

// Agent runtime
export type {
  AgentMessage,
  AgentContentPart,
  AgentModelCapabilities,
  AgentTokenUsage,
  AgentToolCall,
  AgentToolArgumentError,
  AgentToolDefinition,
  AgentProviderRequest,
  AgentPromptCachePolicy,
  AgentPromptCacheMode,
  AgentPromptCacheTtl,
  AgentProviderResult,
  AgentProvider,
  AgentProviderRegistryPort,
  ReasoningEffort,
  AgentToolGateway,
  AgentTurnContext,
  AgentPrompt,
  PromptLoaderPort,
  ReviewPromptKind,
  ReviewState,
  ReviewStateStorePort,
  DocsHit,
  DocSummary,
  DocContent,
  DocsIndexPort,
  SubagentProviderCandidate,
  SubagentResolveRequest,
  SubagentResolveResult,
  SubagentRoutingInfo,
  SubagentRunRequest,
  SubagentRunResult,
  SubagentPort,
  AcpProviderResolverPort,
  AgentTurnRunnerDeps,
  RunAgentTurnInput,
  AgentTurnResult,
  AgentSteerBoundary,
  AgentToolExecution,
  AgentToolResult,
  AgentToolStatus,
  AgentToolContent,
  AgentToolResultMeta,
  AgentToolResultError,
  McpRawResult,
  McpIngestedResult,
  McpContentPart,
  successToolResult,
  errorToolResult,
  cancelledToolResult,
  timeoutToolResult,
  fromGatewayValue,
  fromThrownError,
  ingestMcpToolResult,
  fromIngestedMcp,
  projectModelToolResult,
  truncateToolResultText,
  AgentTurnWorker,
  AgentProviderStrategy,
  RoutedAgentProviderOptions,
  PromptVars,
  RuntimeOsProbe,
  RunAgentTurnCommand,
  CancelAgentTurnCommand,
  CancelAgentTurnResult,
  AgentTurnPartial,
  AnswerAskQuestionCommand,
  AskAnswerVia,
  AskQuestionAnswer,
  AskQuestionOption,
  AskQuestionPendingNotice,
  AskQuestionRequest,
  AskQuestionResult,
  AskQuestionServiceOptions,
  ActiveTurnOpenTool,
  ActiveTurnStreaming,
  ActiveTurnSteer,
  ActiveTurnSnapshot,
  ActiveTurnStartInput,
  ActiveTurnProjectionPort,
  GetActiveTurnQuery,
  GetActiveTurnResult,
  ManageTodosCommand,
  ManageTodosResult,
  KillToolJobCommand,
  SteerAgentTurnCommand,
  CancelAgentSteerCommand,
  ToolJobListQuery,
  ConversationTodoPort,
} from "./agent/index.js";
export {
  AgentTurnRunner,
  McpAgentToolGateway,
  ReviewAgentToolGateway,
  BackgroundReviewScheduler,
  InProcessAgentTurnWorker,
  RoutedAgentProvider,
  AgentTurnCoordinator,
  StreamSeqRegistry,
  InMemoryActiveTurnProjection,
  resolveModelContextDefaults,
  DEFAULT_UNKNOWN_CONTEXT_WINDOW,
  DEFAULT_UNKNOWN_MAX_OUTPUT,
  MIN_AGENTIC_CONTEXT_WINDOW,
  AskQuestionService,
  RunAgentTurnHandler,
  CancelAgentTurnHandler,
  AnswerAskQuestionHandler,
  ManageTodosHandler,
  KillToolJobHandler,
  SteerAgentTurnHandler,
  CancelAgentSteerHandler,
  GetActiveTurnHandler,
  ToolJobListHandler,
  injectPrompts,
  applyVars,
  SYSTEM_PREFIX_END_MARKER,
  stableCurrentDate,
  machineCurrentTime,
  machineTimeZone,
  type PromptInjectionSummary,
  type InjectPromptsResult,
  detectRuntimeOs,
  formatMemoryPrompt,
  formatTodoPrompt,
  type AgentTodoItem,
  type AgentTodoStatus,
  type AgentTodoList,
  type AgentTodoSummary,
  summarizeTodos,
  InMemoryConversationTodoPort,
  AsyncToolRuntime,
  type AsyncToolHandle,
  type AsyncToolStatus,
  type AsyncToolKind,
  type AsyncToolEndReason,
  type AsyncToolSpawnInput,
  type AsyncToolPeekResult,
  type AsyncToolWaitResult,
  type AsyncToolRuntimeOptions,
  execAsyncRun,
  execAsyncWait,
  execAsyncPeek,
  execAsyncKill,
  type AsyncRunContext,
  decideAutoContinue,
  normalizeMaxAutoContinues,
  DEFAULT_MAX_AUTO_CONTINUES,
  MAX_AUTO_CONTINUES_CAP,
  type AutoContinueDecision,
  type AutoContinuePolicyInput,
  type AutoContinueReason,
  SUMMARY_PREFIX,
  COMPACT_USER_MESSAGE_MAX_TOKENS,
  MIN_SUMMARY_CHARS,
  isSummaryMessage,
  collectUserMessages,
  buildCompactedHistory,
  MCP_LIVE_TOOLS_CAP,
  type McpLiveSnapshot,
  type McpLiveSnapshotTool,
  DEFAULT_REVIEW_SETTINGS,
  createSubagentRunStartedEvent,
  createSubagentRunEndedEvent,
  type AgentRuntimeSettings,
  type SubagentRunStartedEvent,
  type SubagentRunEndedEvent,
} from "./agent/index.js";
export type {
  WriteOrigin,
  SkillApprovalStagingPort,
  BackgroundReviewSettings,
  BackgroundReviewSchedulerDeps,
} from "./agent/index.js";

// Config
export { type AppConfig, type TelemetryConfig, loadConfig } from "./config/index.js";

// Token-efficiency telemetry
export type {
  TelemetryTokenUsage,
  ProviderRequestTelemetry,
  AgentTurnTelemetry,
  SteeringTelemetry,
  TelemetryRecord,
  TelemetryPort,
  BuildTurnTelemetryInput,
  MillisClock,
  TelemetryQueryPort,
  TelemetryReadOptions,
  TelemetryReport,
  DailyTurnSummary,
  RecentTurn,
  TelemetryGetReportQuery,
  TelemetryGetReportResult,
  RecordSteeringCommand,
} from "./telemetry/index.js";
export {
  NullTelemetryPort,
  NullTelemetryQueryPort,
  toTelemetryUsage,
  freshInputTokens,
  cacheHitRate,
  buildTurnTelemetry,
  TelemetryAgentProvider,
  withTelemetry,
  TelemetryGetReportHandler,
  computeTelemetryReport,
  RecordSteeringHandler,
} from "./telemetry/index.js";

// System queries
export type { SystemPingQuery, SystemPingResult, SystemVersionQuery, SystemVersionResult } from "./system/index.js";
export { SystemPingHandler, SystemVersionHandler } from "./system/index.js";

// MCP capability queries
export type { GetPromptQuery, ListPromptsQuery, ListResourcesQuery, ListResourceTemplatesQuery, ReadResourceQuery } from "./mcp/index.js";
export { GetPromptHandler, ListPromptsHandler, ListResourcesHandler, ListResourceTemplatesHandler, ReadResourceHandler } from "./mcp/index.js";

// Local Agent Skills
export type {
  SkillDetail,
  SkillFileEntry,
  SkillReadResult,
  SkillRegistryPort,
  SkillSummary,
  SkillRequirements,
  ArchivedSkillSummary,
  SkillOrigin,
  SkillProvenanceEntry,
  SkillProvenancePort,
  SkillState,
  UsageBumpKind,
  SkillUsageRecord,
  SkillUsagePort,
  CuratorStateStorePort,
} from "./skill/index.js";
export { latestActivityAt } from "./skill/index.js";
export {
  SkillCuratorService,
  type CuratorSettings,
  type CuratorChange,
  type CuratorResult,
  type SkillCuratorDeps,
  DEFAULT_CURATOR_SETTINGS,
} from "./skill/index.js";
export {
  SkillCuratorScheduler,
  type CuratorSchedulerSettings,
  type SkillCuratorSchedulerDeps,
  DEFAULT_SCHEDULER_SETTINGS,
} from "./skill/index.js";
// Skills catalog (always-injected Layer-1 prompt block)
export {
  buildSkillsCatalogPrompt,
  SKILLS_CATALOG_BUDGET_CHARS,
  SKILLS_CATALOG_DESC_CAP,
} from "./agent/services/skills-catalog-formatter.js";

// Runtime hydration (hidden synthetic transcript)
export {
  RuntimeHydrationBuilder,
  HYDRATE_ID_PREFIX,
  extractLatestRuntimeHydration,
  type RuntimeContextSnapshot,
} from "./agent/services/runtime-hydration.js";

// Agent Memory
export type {
  MemoryTarget,
  MemoryEntry,
  MemoryUsage,
  MemorySnapshot,
  MemoryMutationResult,
  MemoryStorePort,
} from "./memory/index.js";
export {
  MEMORY_LIMIT,
  USER_LIMIT,
  ENTRY_DELIMITER,
  limitFor,
  splitEntries,
  joinEntries,
  charsOf,
  usageOf,
  checkCapacity,
  findUniqueMatch,
  MATCH_AMBIGUOUS,
  MATCH_NOT_FOUND,
  MATCH_EMPTY,
  addEntry,
  replaceEntry,
  removeEntry,
} from "./memory/index.js";

// Learning graph
export {
  LearningGraphService,
  type LearningGraphDeps,
  type LearningNode,
  type LearningEdge,
  type LearningCluster,
  type LearningGraphStats,
  type LearningGraph,
  type LearningNodeDetail,
  type MutationResult,
  parseMemoryNodeId,
  parseRelatedSkills,
} from "./learning/index.js";

// ACP external agents
export type {
  AcpProviderDescriptor,
  AcpContentBlock,
  AcpToolKind,
  AcpToolStatus,
  AcpToolCall,
  AcpPlanStep,
  AcpPermissionOption,
  AcpPermissionRequest,
  AcpPermissionAnswer,
  AcpAskOption,
  AcpAskRequest,
  AcpAskAnswer,
  AcpClientEvent,
  AcpSessionState,
  AcpClientSink,
  AcpClientPort,
  AcpConfigOption,
  AcpConfigOptionValue,
  AcpResolverCandidate,
  AcpResolverResult,
  AcpSessionInfo,
  AcpSessionServiceDeps,
  RunAcpTurnCommand,
  CancelAcpTurnCommand,
  AnswerAcpPermissionCommand,
  AnswerAcpAskCommand,
  SetAcpConfigOptionCommand,
  SetAcpConfigOptionResult,
  EnsureAcpSessionCommand,
  EnsureAcpSessionResult,
  ProbeAcpProviderCommand,
  ProbeAcpProviderResult,
  ImportAcpModelsCommand,
  ImportAcpModelsResult,
  GetAcpSessionInfoQuery,
  GetAcpSessionInfoResult,
} from "./acp/index.js";
export {
  AcpSessionService,
  AcpPermissionService,
  AcpAskBridgeService,
  RunAcpTurnHandler,
  CancelAcpTurnHandler,
  AnswerAcpPermissionHandler,
  AnswerAcpAskHandler,
  SetAcpConfigOptionHandler,
  EnsureAcpSessionHandler,
  ProbeAcpProviderHandler,
  ImportAcpModelsHandler,
  GetAcpSessionInfoHandler,
} from "./acp/index.js";

// Job automation waist
export type {
  Job,
  JobSchedule,
  JobTrigger,
  JobMode,
  JobStatus,
  JobOutputEntry,
  Condition,
  ConditionNode,
  OnCompleteEmit,
  Pipeline,
  PipelineStep,
  PipelineStepAction,
  PipelineSettings,
  PipelineContext,
  PipelineStepResult,
  PipelineRunResult,
  PipelineStatus,
  PipelineRun,
  PipelineStepRun,
  PipelineRunStatus,
  PipelineTriggerSource,
  PipelineStorePort,
  PipelineExecutorPort,
  PipelineCallToolPort,
  PipelineSchedulerDeps,
  PipelineRunOutcome,
  JobStorePort,
  JobFsPort,
  JobAgentExecutorSettings,
  JobAgentExecutorDeps,
  JobAgentRunOptions,
  JobExecutionResult,
  JobSchedulerSettings,
  JobSchedulerDeps,
  AddJobCommand,
  UpdateJobCommand,
  SetJobEnabledCommand,
  RunJobNowCommand,
  RunJobNowResult,
  RemoveJobCommand,
  RemoveJobResult,
  CancelJobCommand,
  CancelJobResult,
  ListJobsQuery,
  ListJobsResult,
  JobOutputQuery,
  JobOutputResult,
  JobOutputItem,
  ValidateScheduleQuery,
  ValidateScheduleResult,
} from "./job/index.js";
export {
  detectCycle,
  topologicalSort,
  validatePipeline,
  validatePipelineTrigger,
  isPipelineSelfEventPattern,
  nextRunAtForPipelineTrigger,
  scheduleOfPipeline,
  isTerminalPipelineRunStatus,
  PipelineScheduler,
  DEFAULT_PIPELINE_LEASE_TTL_MS,
  PipelineTriggerCoordinator,
  DEFAULT_PIPELINE_TRIGGER_SETTINGS,
} from "./job/index.js";
export {
  ONCE_GRACE_SECONDS,
  recurringCatchupGraceSeconds,
  isRecurring,
  normalizeTrigger,
  scheduleOf,
  parseSchedule,
  computeNextRun,
  describeSchedule,
  ScheduleParseError,
  JobAgentToolGateway,
  JobAgentExecutor,
  DEFAULT_JOB_EXECUTOR_SETTINGS,
  describeMode,
  JobScheduler,
  EventJobMatcher,
  matchGlob,
  evaluateCondition,
  evaluateConditionNode,
  resolveDotPath,
  resolveTemplates,
  resolveTemplatesInRecord,
  templateContextFromEvent,
  type TemplateContext,
  DEFAULT_JOB_SCHEDULER_SETTINGS,
  AddJobHandler,
  UpdateJobHandler,
  SetJobEnabledHandler,
  RunJobNowHandler,
  RemoveJobHandler,
  CancelJobHandler,
  ListJobsHandler,
  JobOutputHandler,
  ValidateScheduleHandler,
  ListPipelinesHandler,
  type ListPipelinesQuery,
  type ListPipelinesResult,
  ListPipelineRunsHandler,
  type ListPipelineRunsQuery,
  type ListPipelineRunsResult,
  GetPipelineRunHandler,
  type GetPipelineRunQuery,
  type GetPipelineRunResult,
  AddPipelineHandler,
  UpdatePipelineHandler,
  RemovePipelineHandler,
  RunPipelineHandler,
  CancelPipelineHandler,
  type AddPipelineCommand,
  type UpdatePipelineCommand,
  type RemovePipelineCommand,
  type RunPipelineCommand,
  type RunPipelineResult,
  type CancelPipelineCommand,
  type CancelPipelineResult,
} from "./job/index.js";

export type { AiConfigurationPort } from "./ai/index.js";
export type {
  ConfigureAiCommand,
  ConfigureAiRuntimeCommand,
  RemoveAiCommand,
} from "./ai/index.js";
export {
  ConfigureAiHandler,
  ConfigureAiRuntimeHandler,
  RemoveAiHandler,
} from "./ai/index.js";
